### ISSUE TITLE
Gnose repetida

### ISSUE THREAD

**Issue by BragaSoterasVinicius** [BragaSoterasVinicius/Bot-da-Gnose#2]
O menino (bot da gnose) quando tenta converter uma palavra repetida em uma frase, acaba por converter todas as palavras iguais à ela naquela msm frase. 
![image](https://github.com/BragaSoterasVinicius/Bot-da-Gnose/assets/60852344/aca29061-d111-4201-a165-8e32f5e6072d)

**Comment by FelipeFTN** [comment]
Para limitar o nível de gnose no servidor, o ideal é usar um limitador na hora de fazer o replace na string em Python:

**Código original**
`originalString.replace(originalString.split(" ")[randomWord], "gnose")`

**Código com limitador:**
`originalString.replace(originalString.split(" ")[randomWord], "gnose", 1)`

Com sorte isso deve garantir que tenhamos um nível aceitável de gnose entre os casas 🙏
